/* ======================================================================
   PART 2b: Hint logic, save, code output, file handling, initialization
   ====================================================================== */
window.updateSelectedIndex=function(val){if(!currentSelectedKey)return;const idx=parseInt(val)||0;const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(hintSymbolsData[cat]&&hintSymbolsData[cat][currentSelectedKey]){hintSymbolsData[cat][currentSelectedKey].selectedIndex=idx;}});};
window.updateHintWidth=function(val){if(!currentSelectedKey)return;const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];const widthVal=parseInt(val);cats.forEach(cat=>{if(hintSymbolsData[cat]&&hintSymbolsData[cat][currentSelectedKey]){if(widthVal>0){hintSymbolsData[cat][currentSelectedKey].size={width:widthVal,height:53};}else{delete hintSymbolsData[cat][currentSelectedKey].size;}}});};

let draggedHintIndex=null;
window.handleDragStart=function(e,index){draggedHintIndex=index;setTimeout(()=>{e.target.closest('.hint-item').classList.add('dragging');},0);e.dataTransfer.effectAllowed='move';};
window.handleDragOver=function(e,index){e.preventDefault();e.dataTransfer.dropEffect='move';if(draggedHintIndex===null||draggedHintIndex===index)return;const item=e.target.closest('.hint-item');if(item){const rect=item.getBoundingClientRect();const midY=rect.top+rect.height/2;document.querySelectorAll('.hint-item').forEach(el=>{el.style.borderTop='';el.style.borderBottom='';});if(e.clientY<midY){item.style.borderTop='2px solid var(--ios-blue)';}else{item.style.borderBottom='2px solid var(--ios-blue)';}}};
window.handleDragLeave=function(e){const item=e.target.closest('.hint-item');if(item){item.style.borderTop='';item.style.borderBottom='';}};
window.handleDrop=function(e,targetIndex){e.preventDefault();document.querySelectorAll('.hint-item').forEach(el=>{el.classList.remove('dragging');el.style.borderTop='';el.style.borderBottom='';});if(draggedHintIndex===null||draggedHintIndex===targetIndex)return;const item=e.target.closest('.hint-item');let finalTargetIndex=targetIndex;if(item){const rect=item.getBoundingClientRect();const midY=rect.top+rect.height/2;if(e.clientY>midY&&draggedHintIndex<targetIndex){}else if(e.clientY<midY&&draggedHintIndex>targetIndex){}else if(e.clientY>midY&&draggedHintIndex>targetIndex){finalTargetIndex++;}else if(e.clientY<midY&&draggedHintIndex<targetIndex){finalTargetIndex--;}}const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(hintSymbolsData[cat]&&hintSymbolsData[cat][currentSelectedKey]&&hintSymbolsData[cat][currentSelectedKey].list){const list=hintSymbolsData[cat][currentSelectedKey].list;const movedItem=list.splice(draggedHintIndex,1)[0];list.splice(finalTargetIndex,0,movedItem);}});draggedHintIndex=null;renderHintItems();};
window.handleDragEnd=function(e){document.querySelectorAll('.hint-item').forEach(el=>{el.classList.remove('dragging');el.style.borderTop='';el.style.borderBottom='';});draggedHintIndex=null;};

function renderHintItems(){const container=document.getElementById('hintItemsContainer');container.innerHTML='';const activeCat=currentCategory==='both'?'alphabetic':currentCategory;if(!hintSymbolsData[activeCat]||!hintSymbolsData[activeCat][currentSelectedKey])return;const dataList=hintSymbolsData[activeCat][currentSelectedKey].list||[];if(dataList.length===0){container.innerHTML='<p style="text-align:center;color:var(--text-secondary);font-size:13px;margin:10px;">目前沒有設定長按選項</p>';return;}
    dataList.forEach((item,index)=>{const div=document.createElement('div');div.className='hint-item';div.draggable=true;div.ondragstart=(e)=>handleDragStart(e,index);div.ondragover=(e)=>handleDragOver(e,index);div.ondragleave=(e)=>handleDragLeave(e);div.ondrop=(e)=>handleDrop(e,index);div.ondragend=(e)=>handleDragEnd(e);
        let actionType='symbol',actionValue='';if(typeof item.action==='string'){actionType=item.action;}else if(item.action){if(item.action.symbol!==undefined){actionType='symbol';actionValue=item.action.symbol;}else if(item.action.character!==undefined){actionType='character';actionValue=item.action.character;}else if(item.action.sendKeys!==undefined){actionType='sendKeys';actionValue=item.action.sendKeys;}else if(item.action.shortcut!==undefined){if(reverseShortcutMap[item.action.shortcut]){actionType=reverseShortcutMap[item.action.shortcut];actionValue='';}else{actionType='shortcut';actionValue=item.action.shortcut;}}else if(item.action.keyboardType!==undefined){actionType='keyboardType';actionValue=item.action.keyboardType;}}
        let displayLabelText="";let previewSymbol="";if(item.label){if(item.label.systemImageName){displayLabelText="sf:"+item.label.systemImageName;previewSymbol=sfSymbolEmojiMap[item.label.systemImageName]||'❖';}else if(item.label.text){displayLabelText=item.label.text;previewSymbol=Array.from(displayLabelText)[0]||'';}}
        const showValueInput=!noValueCommands.includes(actionType)&&!actionType.startsWith('shortcut_');
        let actionValueHtml=`<input type="text" style="width:145px;" value="${actionValue}" onchange="updateHintItem(${index},'actionValue',this.value,false)">`;
        if(actionType==='shortcut'){let isMatched=shortCommandsGroups.flatMap(g=>g.options).some(c=>c.value===actionValue);let isCustom=item._isCustomUI||(!isMatched&&actionValue!=='');let optionsHtml=`<option value="" ${!actionValue&&!isCustom?'selected disabled':''}>選擇...</option>`;shortCommandsGroups.forEach(g=>{optionsHtml+=`<optgroup label="${g.group}">`+g.options.map(c=>`<option value="${c.value}" ${actionValue===c.value&&!isCustom?'selected':''}>${c.label}</option>`).join('')+`</optgroup>`;});optionsHtml+=`<option value="__custom__" ${isCustom?'selected':''}>自訂</option>`;actionValueHtml=`<div style="display:flex;flex-direction:column;gap:4px;width:145px;"><select style="width:145px;" onchange="updateHintShortcut(${index},this.value)">${optionsHtml}</select><input type="text" style="display:${isCustom?'block':'none'};width:145px;" placeholder="指令" value="${actionValue}" onchange="updateHintItem(${index},'actionValue',this.value,false)"></div>`;}
        else if(actionType==='keyboardType'){let isMatched=keyboardTypesList.some(kb=>kb.value===actionValue);let isCustom=item._isCustomKbUI||(!isMatched&&actionValue!=='');let optionsHtml=`<option value="" ${!actionValue&&!isCustom?'selected disabled':''}>請選擇鍵盤...</option>`;optionsHtml+=keyboardTypesList.map(kb=>`<option value="${kb.value}" ${actionValue===kb.value&&!isCustom?'selected':''}>${kb.label}</option>`).join('');optionsHtml+=`<option value="__custom__" ${isCustom?'selected':''}>自訂名稱</option>`;actionValueHtml=`<div style="display:flex;flex-direction:column;gap:4px;width:145px;"><select style="width:145px;" onchange="updateHintKeyboardType(${index},this.value)">${optionsHtml}</select><input type="text" style="display:${isCustom?'block':'none'};width:145px;" placeholder="輸入鍵盤名稱" value="${actionValue}" onchange="updateHintItem(${index},'actionValue',this.value,false)"></div>`;}
        let actionSelectHtml=`<select style="width:145px;" onchange="updateHintItem(${index},'actionType',this.value,true)"><optgroup label="常用快捷指令"><option value="shortcut_undo" ${actionType==='shortcut_undo'?'selected':''}>撤銷</option><option value="shortcut_deleteText" ${actionType==='shortcut_deleteText'?'selected':''}>全刪除</option><option value="shortcut_copy" ${actionType==='shortcut_copy'?'selected':''}>複製</option><option value="shortcut_paste" ${actionType==='shortcut_paste'?'selected':''}>貼上</option><option value="shortcut_cut" ${actionType==='shortcut_cut'?'selected':''}>剪下</option><option value="shortcut_selectText" ${actionType==='shortcut_selectText'?'selected':''}>全選</option><option value="shortcut_home" ${actionType==='shortcut_home'?'selected':''}>行首</option><option value="shortcut_end" ${actionType==='shortcut_end'?'selected':''}>行尾</option><option value="shortcut_onehanded" ${actionType==='shortcut_onehanded'?'selected':''}>單手</option><option value="shortcut_rime2" ${actionType==='shortcut_rime2'?'selected':''}>次選</option><option value="shortcut_rime3" ${actionType==='shortcut_rime3'?'selected':''}>三選</option></optgroup><optgroup label="獨立指令"><option value="backspace" ${actionType==='backspace'?'selected':''}>退格</option><option value="enter" ${actionType==='enter'?'selected':''}>回車</option><option value="shift" ${actionType==='shift'?'selected':''}>Shift</option><option value="tab" ${actionType==='tab'?'selected':''}>Tab</option><option value="space" ${actionType==='space'?'selected':''}>空格</option><option value="nextKeyboard" ${actionType==='nextKeyboard'?'selected':''}>地球</option><option value="characterMargin" ${actionType==='characterMargin'?'selected':''}>佔位</option><option value="none" ${actionType==='none'?'selected':''}>無</option></optgroup><optgroup label="需要設定值"><option value="character" ${actionType==='character'?'selected':''}>字符</option><option value="symbol" ${actionType==='symbol'?'selected':''}>符號</option><option value="sendKeys" ${actionType==='sendKeys'?'selected':''}>組合鍵</option><option value="shortcut" ${actionType==='shortcut'?'selected':''}>自訂命令</option><option value="keyboardType" ${actionType==='keyboardType'?'selected':''}>鍵盤</option></optgroup></select>`;
        div.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;width:100%;margin-bottom:8px;padding-bottom:8px;border-bottom:1px dashed var(--border);"><span class="hint-index-badge" title="拖曳以改變順序">選項 [${index}] ↕️</span><button class="btn btn-red btn-sm" onclick="removeHintItem(${index})">🗑️ 刪除</button></div><div class="input-row" style="margin-bottom:4px;"><label>輸出類型:</label>${actionSelectHtml}</div><div class="input-row" style="margin-bottom:4px;display:${showValueInput?'flex':'none'};"><label>輸出內容:</label>${actionValueHtml}</div><div class="input-row" style="margin-bottom:4px;"><label>鍵盤顯示:</label><div style="display:flex;gap:4px;align-items:center;"><div class="sf-input-container" style="width:115px;"><div class="sf-preview-box">${previewSymbol}</div><input type="text" class="sf-label-input" value="${displayLabelText}" onchange="updateHintItemLabel(${index},this.value)" placeholder="sf:..."></div><button class="btn btn-ghost btn-sm" style="padding:0;width:26px;height:32px;" onclick="openIconModal(${index})" title="選擇圖示">🔍</button></div></div>`;
        container.appendChild(div);});
}

window.updateHintShortcut=function(index,value){const catsToUpdate=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];if(value==='__custom__'){catsToUpdate.forEach(cat=>hintSymbolsData[cat][currentSelectedKey].list[index]._isCustomUI=true);updateHintItem(index,'actionValue','',true);}else{catsToUpdate.forEach(cat=>hintSymbolsData[cat][currentSelectedKey].list[index]._isCustomUI=false);const matchedCmd=shortCommandsGroups.flatMap(g=>g.options).find(c=>c.value===value);if(matchedCmd){updateHintItemLabel(index,matchedCmd.label);}updateHintItem(index,'actionValue',value,true);}};
window.updateHintKeyboardType=function(index,value){const catsToUpdate=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];if(value==='__custom__'){catsToUpdate.forEach(cat=>hintSymbolsData[cat][currentSelectedKey].list[index]._isCustomKbUI=true);updateHintItem(index,'actionValue','',true);}else{catsToUpdate.forEach(cat=>hintSymbolsData[cat][currentSelectedKey].list[index]._isCustomKbUI=false);const matchedKb=keyboardTypesList.find(k=>k.value===value);if(matchedKb){updateHintItemLabel(index,matchedKb.label.split(' ')[0]);}updateHintItem(index,'actionValue',value,true);}};
window.updateHintItemLabel=function(index,value){const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(!hintSymbolsData[cat][currentSelectedKey].list[index])hintSymbolsData[cat][currentSelectedKey].list[index]={action:{symbol:''}};const item=hintSymbolsData[cat][currentSelectedKey].list[index];let v=value.trim();if(v){item.label={};if(v.toLowerCase().startsWith('sf:')){item.label.systemImageName=v.substring(3).trim();}else{item.label.text=v;}}else{item.label={text:""};}});renderHintItems();}
window.updateHintItem=function(index,field,value,forceRender){const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(!hintSymbolsData[cat][currentSelectedKey].list[index])hintSymbolsData[cat][currentSelectedKey].list[index]={action:{symbol:''},label:{text:''}};const item=hintSymbolsData[cat][currentSelectedKey].list[index];let actionType=typeof item.action==='string'?item.action:(item.action?Object.keys(item.action)[0]:'symbol');let aVal=typeof item.action==='string'?'':(item.action?item.action[actionType]:'');if(item.action&&item.action.shortcut){if(reverseShortcutMap[item.action.shortcut]){actionType=reverseShortcutMap[item.action.shortcut];}else{actionType='shortcut';}}if(field==='actionType'){actionType=value;if(noValueCommands.includes(actionType)||actionType.startsWith('shortcut_'))aVal='';if(actionType==='shortcut'){aVal='';item._isCustomUI=false;}if(actionType==='keyboardType'){aVal='';item._isCustomKbUI=false;}if(actionType.startsWith('shortcut_')){item.action={"shortcut":presetShortcuts[actionType]};}else if(noValueCommands.includes(actionType)){item.action=actionType;}else{item.action={};item.action[actionType]=aVal;}if(commandToSfMap[actionType]){item.label={systemImageName:commandToSfMap[actionType].substring(3).trim()};}else{item.label={text:""};}}else if(field==='actionValue'){aVal=value;if(!actionType.startsWith('shortcut_')&&!noValueCommands.includes(actionType)){item.action={};item.action[actionType]=aVal;}}});if(forceRender)renderHintItems();};
window.addHintItem=function(){const newItem={action:{symbol:''},label:{text:''}};const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(!hintSymbolsData[cat][currentSelectedKey].list)hintSymbolsData[cat][currentSelectedKey].list=[];hintSymbolsData[cat][currentSelectedKey].list.push(JSON.parse(JSON.stringify(newItem)));});renderHintItems();};
window.removeHintItem=function(index){const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(hintSymbolsData[cat][currentSelectedKey].list[index])hintSymbolsData[cat][currentSelectedKey].list.splice(index,1);});renderHintItems();};

function silentSaveCurrentKey(){if(!currentSelectedKey)return;const nUp=buildSwipeNode('up',swipeData.swipe_up[currentSelectedKey]);if(nUp)swipeData.swipe_up[currentSelectedKey]=nUp;else delete swipeData.swipe_up[currentSelectedKey];const nDown=buildSwipeNode('down',swipeData.swipe_down[currentSelectedKey]);if(nDown)swipeData.swipe_down[currentSelectedKey]=nDown;else delete swipeData.swipe_down[currentSelectedKey];const idx=parseInt(document.getElementById('selectedIndexInput').value)||0;const widthVal=parseInt(document.getElementById('hintWidthInput').value)||0;const cats=currentCategory==='both'?['alphabetic','pinyin']:[currentCategory];cats.forEach(cat=>{if(hintSymbolsData[cat]&&hintSymbolsData[cat][currentSelectedKey]){hintSymbolsData[cat][currentSelectedKey].selectedIndex=idx;if(widthVal>0){hintSymbolsData[cat][currentSelectedKey].size={width:widthVal,height:53};}else{delete hintSymbolsData[cat][currentSelectedKey].size;}if(hintSymbolsData[cat][currentSelectedKey].list.length===0)delete hintSymbolsData[cat][currentSelectedKey];}});}
function saveKeyData(){if(!currentSelectedKey)return;silentSaveCurrentKey();renderKeyboard();updateCodeOutput();const btn=document.getElementById('mainSaveBtn');const originalText=btn.innerText;btn.innerText='✅ 更新成功！已產出最新程式碼';setTimeout(()=>btn.innerText=originalText,3000);}
function batchUpdate(direction){if(currentSelectedKey)silentSaveCurrentKey();const sizeStr=document.getElementById(direction==='up'?'batchUpSize':'batchDownSize').value;const color=document.getElementById(direction==='up'?'batchUpColor':'batchDownColor').value;const size=sizeStr?parseInt(sizeStr):null;const targetData=direction==='up'?swipeData.swipe_up:swipeData.swipe_down;for(let key in targetData){if(targetData.hasOwnProperty(key)){if(size!==null)targetData[key].fontSize=size;if(color.toLowerCase()!=='#8e8e93'){targetData[key].normalColor=targetData[key].highlightColor=color;}}}renderKeyboard();updateCodeOutput();if(currentSelectedKey)selectKey(currentSelectedKey);}
function switchCodeTab(tab){activeCodeTab=tab;document.getElementById('tabBtnSwipe').className=tab==='swipe'?'btn btn-primary btn-sm':'btn btn-ghost btn-sm';document.getElementById('tabBtnHint').className=tab==='hint'?'btn btn-primary btn-sm':'btn btn-ghost btn-sm';document.getElementById('codeTitle').innerText=tab==='swipe'?'程式碼預覽 ('+fileNames.swipe+')':'程式碼預覽 ('+fileNames.hint+')';updateCodeOutput();}
function updateCodeOutput(){if(activeCodeTab==='swipe'){document.getElementById('codeOutput').value="// === 本配置檔由鍵盤配置工作室產出 ===\n\n"+JSON.stringify(swipeData,null,2);}else{let cleanData=JSON.parse(JSON.stringify(hintSymbolsData));Object.keys(cleanData).forEach(c=>Object.keys(cleanData[c]).forEach(k=>{if(cleanData[c][k].list){cleanData[c][k].list.forEach(i=>{delete i._isCustomUI;delete i._isCustomKbUI;if(!i.label){i.label={text:""};}else if(Object.keys(i.label).length===0){i.label={text:""};}});}}));let out=JSON.stringify(cleanData,null,2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)\":/g,'$1:');document.getElementById('codeOutput').value="// === 本配置檔由鍵盤配置工作室產出 ===\n\n{\n"+out.substring(1,out.length-1)+"\n}";}}

function setupDropZone(dzId,inputId,textId,type,callback){const dz=document.getElementById(dzId),input=document.getElementById(inputId);dz.onclick=()=>input.click();dz.ondragover=e=>{e.preventDefault();dz.classList.add('dragover');};dz.ondragleave=()=>dz.classList.remove('dragover');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('dragover');if(e.dataTransfer.files.length){if(type==='swipe')fileNames.swipe=e.dataTransfer.files[0].name;if(type==='hint')fileNames.hint=e.dataTransfer.files[0].name;callback(e.dataTransfer.files[0],textId);}};input.onchange=e=>{if(e.target.files.length){if(type==='swipe')fileNames.swipe=e.target.files[0].name;if(type==='hint')fileNames.hint=e.target.files[0].name;callback(e.target.files[0],textId);}input.value='';};}
function showBtnMsg(btnId,defaultText,msg){const b=document.getElementById(btnId);b.innerText=msg;setTimeout(()=>b.innerText=defaultText,2000);}
window.handlePanelCopy=function(type){if(currentSelectedKey){silentSaveCurrentKey();updateCodeOutput();renderKeyboard();}if(activeCodeTab!==type)switchCodeTab(type);const text=document.getElementById('codeOutput').value;internalClipboard[type]=text;const btnId=type==='swipe'?'copySwipeBtn':'copyHintBtn';const defaultText=type==='swipe'?'📄 複製上下滑配置':'📄 複製長按配置';if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(()=>showBtnMsg(btnId,defaultText,'✅ 複製成功')).catch(()=>showBtnMsg(btnId,defaultText,'✅ 暫存複製'));}else{showBtnMsg(btnId,defaultText,'✅ 暫存複製');}};
window.handlePanelPaste=async function(type){let txt="";try{if(navigator.clipboard&&navigator.clipboard.readText)txt=await navigator.clipboard.readText();}catch(err){}if(!txt)txt=internalClipboard[type];const btnId=type==='swipe'?'pasteSwipeBtn':'pasteHintBtn';const defaultText=type==='swipe'?'📋 貼上上下滑配置':'📋 貼上長按配置';if(!txt){showBtnMsg(btnId,defaultText,'❌ 無內容可貼上');return;}try{if(type==='swipe'){swipeData=parseDataFile(txt);step2Loaded=true;}else{hintSymbolsData=parseDataFile(txt);migrateOldCommands(hintSymbolsData);step3Loaded=true;}if(activeCodeTab!==type)switchCodeTab(type);renderKeyboard();updateCodeOutput();if(currentSelectedKey)selectKey(currentSelectedKey);showBtnMsg(btnId,defaultText,'✅ 貼上成功');}catch(e){showBtnMsg(btnId,defaultText,'❌ 解析失敗');}};
